Client Authorization Token support
pelotontech/Peloton-EPP-.Net-4.5-SDK pull request #13
Opened 2017-02-28 22:20 UTC by fraserd

Implemented support for the Client Authorization Token endpoint.

@cattiwill, @dandersonpeloton, @sleepypapa, please review.

2017-03-01 02:59 UTC, cattiwill requested changes

2017-03-01 02:59 UTC, cattiwill commented on PelotonEppSdk/Enums/ClientAuthTokenAuthorizationType.cs
> +        CreditCard = 1,
These should match our internal API. I recommend CARD = 0 and BANK = 1 for now.

2017-03-01 02:59 UTC, cattiwill commented on PelotonEppSdk/Interfaces/IClientAuthTokenCreateRequest.cs
> +        [StringLength(128)]
StringLength should this be larger probably something like 2048

2017-03-01 02:59 UTC, cattiwill commented on PelotonEppSdk/Models/ClientAuthTokenResponse.cs
> +
Additional line here

2017-03-01 02:59 UTC, cattiwill commented on PelotonEppSdkTests/ClientAuthTokenTests.cs
> +            Assert.AreEqual("2017-02-27 21:30:58", getResult.AuthorizedDatetime.ToString());
I think this test will always fail or will fail at some point if you are checking a static date.

2017-03-01 03:04 UTC, fraserd commented on PelotonEppSdk/Interfaces/IClientAuthTokenCreateRequest.cs
> +        [StringLength(128)]
The length was based on other URL-storage columns in the EPP DB.

2017-03-01 03:12 UTC, cattiwill commented on PelotonEppSdk/Interfaces/IClientAuthTokenCreateRequest.cs
> +        [StringLength(128)]
Wouldn't it have been 256 instead of 128 then ;-)

2017-03-01 03:15 UTC, fraserd commented on PelotonEppSdk/Enums/ClientAuthTokenAuthorizationType.cs
> +        CreditCard = 1,
CARD and BANK are not very descriptive. What kind of card? What about a bank?

2017-03-01 03:16 UTC, fraserd commented on PelotonEppSdk/Interfaces/IClientAuthTokenCreateRequest.cs
> +        [StringLength(128)]
I would have thought so....Yes, you are right. It is 256 in the DB and wrong in the code.

2017-03-01 03:17 UTC, fraserd commented on PelotonEppSdk/Interfaces/IClientAuthTokenCreateRequest.cs
> +        [StringLength(128)]
I'll update it here and in the corresponding C# in EPP

2017-03-01 03:17 UTC, fraserd commented on PelotonEppSdkTests/ClientAuthTokenTests.cs
> +            Assert.AreEqual("2017-02-27 21:30:58", getResult.AuthorizedDatetime.ToString());
Yes, that is correct. I will refactor the test.

2017-03-03 05:39 UTC, cattiwill requested changes

2017-03-03 05:39 UTC, cattiwill commented on PelotonEppSdk/Interfaces/IClientAuthTokenCreateRequest.cs
> +        [StringLength(2048)]
+1

2017-03-03 05:39 UTC, cattiwill commented on PelotonEppSdk/Enums/ClientAuthTokenAuthorizationType.cs
> +        CreditCard = 1,
Card = Card Interactions (Add Card / Update Card / Delete Card)
BankAccount = BankAccount Interactions (Add Bank Account / Update Bank Account / Delete Bank Account)

This is all we are going to support with this release the others should be deleted for now.

2017-03-04 20:30 UTC, cattiwill approved these changes

2017-03-07 05:06 UTC, cattiwill approved these changes

2017-03-07 15:45 UTC, merged